/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecepcionRouteImport } from './routes/recepcion'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestionLoginRouteImport } from './routes/gestion.login'
import { Route as AppGestionIndexRouteImport } from './routes/_app.gestion.index'
import { Route as AppGestionDashboardRouteImport } from './routes/_app.gestion.dashboard'
import { Route as AppGestionAdminRouteImport } from './routes/_app.gestion.admin'
import { Route as AppGestionPrestacionesIndexRouteImport } from './routes/_app.gestion.prestaciones.index'
import { Route as AppGestionReportesIomaRouteImport } from './routes/_app.gestion.reportes.ioma'
import { Route as AppGestionReportesDiarioRouteImport } from './routes/_app.gestion.reportes.diario'
import { Route as AppGestionPrestacionesNuevaRouteImport } from './routes/_app.gestion.prestaciones.nueva'

const RecepcionRoute = RecepcionRouteImport.update({
  id: '/recepcion',
  path: '/recepcion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionLoginRoute = GestionLoginRouteImport.update({
  id: '/gestion/login',
  path: '/gestion/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGestionIndexRoute = AppGestionIndexRouteImport.update({
  id: '/gestion/',
  path: '/gestion/',
  getParentRoute: () => AppRoute,
} as any)
const AppGestionDashboardRoute = AppGestionDashboardRouteImport.update({
  id: '/gestion/dashboard',
  path: '/gestion/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGestionAdminRoute = AppGestionAdminRouteImport.update({
  id: '/gestion/admin',
  path: '/gestion/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppGestionPrestacionesIndexRoute =
  AppGestionPrestacionesIndexRouteImport.update({
    id: '/gestion/prestaciones/',
    path: '/gestion/prestaciones/',
    getParentRoute: () => AppRoute,
  } as any)
const AppGestionReportesIomaRoute = AppGestionReportesIomaRouteImport.update({
  id: '/gestion/reportes/ioma',
  path: '/gestion/reportes/ioma',
  getParentRoute: () => AppRoute,
} as any)
const AppGestionReportesDiarioRoute =
  AppGestionReportesDiarioRouteImport.update({
    id: '/gestion/reportes/diario',
    path: '/gestion/reportes/diario',
    getParentRoute: () => AppRoute,
  } as any)
const AppGestionPrestacionesNuevaRoute =
  AppGestionPrestacionesNuevaRouteImport.update({
    id: '/gestion/prestaciones/nueva',
    path: '/gestion/prestaciones/nueva',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recepcion': typeof RecepcionRoute
  '/gestion/login': typeof GestionLoginRoute
  '/gestion/admin': typeof AppGestionAdminRoute
  '/gestion/dashboard': typeof AppGestionDashboardRoute
  '/gestion/': typeof AppGestionIndexRoute
  '/gestion/prestaciones/nueva': typeof AppGestionPrestacionesNuevaRoute
  '/gestion/reportes/diario': typeof AppGestionReportesDiarioRoute
  '/gestion/reportes/ioma': typeof AppGestionReportesIomaRoute
  '/gestion/prestaciones/': typeof AppGestionPrestacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recepcion': typeof RecepcionRoute
  '/gestion/login': typeof GestionLoginRoute
  '/gestion/admin': typeof AppGestionAdminRoute
  '/gestion/dashboard': typeof AppGestionDashboardRoute
  '/gestion': typeof AppGestionIndexRoute
  '/gestion/prestaciones/nueva': typeof AppGestionPrestacionesNuevaRoute
  '/gestion/reportes/diario': typeof AppGestionReportesDiarioRoute
  '/gestion/reportes/ioma': typeof AppGestionReportesIomaRoute
  '/gestion/prestaciones': typeof AppGestionPrestacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/recepcion': typeof RecepcionRoute
  '/gestion/login': typeof GestionLoginRoute
  '/_app/gestion/admin': typeof AppGestionAdminRoute
  '/_app/gestion/dashboard': typeof AppGestionDashboardRoute
  '/_app/gestion/': typeof AppGestionIndexRoute
  '/_app/gestion/prestaciones/nueva': typeof AppGestionPrestacionesNuevaRoute
  '/_app/gestion/reportes/diario': typeof AppGestionReportesDiarioRoute
  '/_app/gestion/reportes/ioma': typeof AppGestionReportesIomaRoute
  '/_app/gestion/prestaciones/': typeof AppGestionPrestacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recepcion'
    | '/gestion/login'
    | '/gestion/admin'
    | '/gestion/dashboard'
    | '/gestion/'
    | '/gestion/prestaciones/nueva'
    | '/gestion/reportes/diario'
    | '/gestion/reportes/ioma'
    | '/gestion/prestaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recepcion'
    | '/gestion/login'
    | '/gestion/admin'
    | '/gestion/dashboard'
    | '/gestion'
    | '/gestion/prestaciones/nueva'
    | '/gestion/reportes/diario'
    | '/gestion/reportes/ioma'
    | '/gestion/prestaciones'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/recepcion'
    | '/gestion/login'
    | '/_app/gestion/admin'
    | '/_app/gestion/dashboard'
    | '/_app/gestion/'
    | '/_app/gestion/prestaciones/nueva'
    | '/_app/gestion/reportes/diario'
    | '/_app/gestion/reportes/ioma'
    | '/_app/gestion/prestaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RecepcionRoute: typeof RecepcionRoute
  GestionLoginRoute: typeof GestionLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recepcion': {
      id: '/recepcion'
      path: '/recepcion'
      fullPath: '/recepcion'
      preLoaderRoute: typeof RecepcionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion/login': {
      id: '/gestion/login'
      path: '/gestion/login'
      fullPath: '/gestion/login'
      preLoaderRoute: typeof GestionLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/gestion/': {
      id: '/_app/gestion/'
      path: '/gestion'
      fullPath: '/gestion/'
      preLoaderRoute: typeof AppGestionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestion/dashboard': {
      id: '/_app/gestion/dashboard'
      path: '/gestion/dashboard'
      fullPath: '/gestion/dashboard'
      preLoaderRoute: typeof AppGestionDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestion/admin': {
      id: '/_app/gestion/admin'
      path: '/gestion/admin'
      fullPath: '/gestion/admin'
      preLoaderRoute: typeof AppGestionAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestion/prestaciones/': {
      id: '/_app/gestion/prestaciones/'
      path: '/gestion/prestaciones'
      fullPath: '/gestion/prestaciones/'
      preLoaderRoute: typeof AppGestionPrestacionesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestion/reportes/ioma': {
      id: '/_app/gestion/reportes/ioma'
      path: '/gestion/reportes/ioma'
      fullPath: '/gestion/reportes/ioma'
      preLoaderRoute: typeof AppGestionReportesIomaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestion/reportes/diario': {
      id: '/_app/gestion/reportes/diario'
      path: '/gestion/reportes/diario'
      fullPath: '/gestion/reportes/diario'
      preLoaderRoute: typeof AppGestionReportesDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gestion/prestaciones/nueva': {
      id: '/_app/gestion/prestaciones/nueva'
      path: '/gestion/prestaciones/nueva'
      fullPath: '/gestion/prestaciones/nueva'
      preLoaderRoute: typeof AppGestionPrestacionesNuevaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppGestionAdminRoute: typeof AppGestionAdminRoute
  AppGestionDashboardRoute: typeof AppGestionDashboardRoute
  AppGestionIndexRoute: typeof AppGestionIndexRoute
  AppGestionPrestacionesNuevaRoute: typeof AppGestionPrestacionesNuevaRoute
  AppGestionReportesDiarioRoute: typeof AppGestionReportesDiarioRoute
  AppGestionReportesIomaRoute: typeof AppGestionReportesIomaRoute
  AppGestionPrestacionesIndexRoute: typeof AppGestionPrestacionesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGestionAdminRoute: AppGestionAdminRoute,
  AppGestionDashboardRoute: AppGestionDashboardRoute,
  AppGestionIndexRoute: AppGestionIndexRoute,
  AppGestionPrestacionesNuevaRoute: AppGestionPrestacionesNuevaRoute,
  AppGestionReportesDiarioRoute: AppGestionReportesDiarioRoute,
  AppGestionReportesIomaRoute: AppGestionReportesIomaRoute,
  AppGestionPrestacionesIndexRoute: AppGestionPrestacionesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RecepcionRoute: RecepcionRoute,
  GestionLoginRoute: GestionLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
